# Generated by Django 5.0.6 on 2024-06-26 19:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lyrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explicit", models.BooleanField(default=False)),
                ("body", models.TextField()),
                ("copyright", models.TextField()),
                ("summary", models.TextField()),
                (
                    "countries",
                    models.ManyToManyField(
                        related_name="lyrics", to="summarizer.country"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lyrics",
                "verbose_name_plural": "Lyrics",
            },
        ),
    ]
