# Generated by Django 5.0.6 on 2024-06-26 19:37
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
        migrations.AlterField(
            model_name="lyrics",
            name="body",
            field=models.TextField(help_text="The main body of the lyrics."),
        ),
        migrations.AlterField(
            model_name="lyrics",
            name="copyright",
            field=models.TextField(help_text="Copyright information for the lyrics."),
        ),
        migrations.AlterField(
            model_name="lyrics",
            name="countries",
            field=models.ManyToManyField(
                help_text="Countries found in the lyrics.",
                related_name="lyrics",
                to="summarizer.country",
            ),
        ),
        migrations.AlterField(
            model_name="lyrics",
            name="explicit",
            field=models.BooleanField(
                default=False, help_text="Indicates whether the lyrics are explicit."
            ),
        ),
        migrations.AlterField(
            model_name="lyrics",
            name="summary",
            field=models.TextField(help_text="A brief summary of the lyrics."),
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Name of the song.", max_length=255),
                ),
                ("artist_id", models.IntegerField(help_text="ID of the artist.")),
                (
                    "artist_name",
                    models.CharField(help_text="Name of the artist.", max_length=255),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating of the song. 0-5 scale.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "explicit",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the song is explicit.",
                    ),
                ),
                (
                    "has_lyrics",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the song has lyrics.",
                    ),
                ),
                ("lyrics", models.TextField(help_text="Lyrics of the song.")),
                (
                    "has_subtitles",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the song has subtitles.",
                    ),
                ),
                ("album_id", models.IntegerField(help_text="ID of the album.")),
                (
                    "album_name",
                    models.CharField(help_text="Name of the album.", max_length=255),
                ),
                (
                    "countries",
                    models.ManyToManyField(
                        help_text="Countries found in the song.",
                        related_name="songs",
                        to="summarizer.country",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
