# Generated by Django 5.0.6 on 2024-06-26 19:42
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer", "0003_delete_lyrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.CharField(help_text="Name of the artist.", max_length=255),
                ),
                (
                    "track",
                    models.CharField(help_text="Name of the track.", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("FOUND", "Found"),
                            ("NOT_FOUND", "Not Found"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROCESSING",
                        help_text="Status of the request.",
                        max_length=255,
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        help_text="Reference to the song.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="summarizer.song",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
