# Generated by Django 5.0.6 on 2024-06-26 20:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer", "0005_request_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="errors",
            field=models.TextField(
                blank=True, help_text="Errors encountered during processing.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("PROCESSING", "Processing"),
                    ("FOUND", "Found"),
                    ("NOT_FOUND", "Not Found"),
                    ("FAILED", "Failed"),
                ],
                default="INITIALIZED",
                help_text="Status of the request.",
                max_length=255,
            ),
        ),
    ]
