# Generated by Django 5.0.6 on 2024-06-27 10:04
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer", "0006_request_errors_alter_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Summary of the song.", null=True
            ),
        ),
    ]
