# Generated by Django 5.0.6 on 2024-06-27 10:28
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer", "0007_song_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("LYRICS_FETCHED", "Lyrics Fetched"),
                    ("SUMMARY_GENERATED", "Summary Generated"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="INITIALIZED",
                help_text="Status of the song.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("PROCESSING", "Processing"),
                    ("SONG_FOUND", "Song Found"),
                    ("LYRICS_FOUND", "Lyrics Found"),
                    ("SUMMARY_GENERATED", "Summary Generated"),
                    ("COMPLETED", "Completed"),
                    ("NOT_FOUND", "Not Found"),
                    ("FAILED", "Failed"),
                ],
                default="INITIALIZED",
                help_text="Status of the request.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="rating",
            field=models.IntegerField(
                help_text="Rating of the song.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
