# Generated by Django 5.0.6 on 2024-06-27 11:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer", "0008_song_status_alter_request_status_alter_song_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPTLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.CharField(help_text="Name of the model.", max_length=255),
                ),
                ("prompt", models.TextField(help_text="Prompt for the model.")),
                ("response", models.TextField(help_text="Response from the model.")),
            ],
            options={
                "verbose_name": "GPT Log",
                "verbose_name_plural": "GPT Logs",
            },
        ),
        migrations.CreateModel(
            name="MusixLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("endpoint", models.TextField(help_text="Endpoint of the request.")),
                ("params", models.JSONField(help_text="Parameters of the request.")),
                ("response", models.JSONField(help_text="Response of the request.")),
                (
                    "status_code",
                    models.IntegerField(help_text="Status code of the response."),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
